# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = "512"
    vb.name = "ceph-basebox"
  end

  config.vm.hostname = "ceph-basebox"
  config.vm.provision "shell", path: "bootstrap.sh"
end
